from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from prefab_sentinel.json_io import dump_json
from prefab_sentinel.smoke_batch_case import (
    _build_cases,
    _default_plan_path,
    _default_project_path,
    _load_timeout_profile_map,
    _wsl_path_exists,
)
from prefab_sentinel.smoke_batch_runner import _execute_batch_cases

_PROJECT_SMOKE_SCRIPT = Path(__file__).resolve().parent.parent / "scripts" / "unity_bridge_smoke.py"
UNITY_BRIDGE_SMOKE_SCRIPT = (
    _PROJECT_SMOKE_SCRIPT
    if _PROJECT_SMOKE_SCRIPT.exists()
    else Path("scripts") / "unity_bridge_smoke.py"
)
DEFAULT_EXECUTE_METHOD = "PrefabSentinel.UnityPatchBridge.ApplyFromJson"
DEFAULT_OUT_DIR = Path("reports") / "bridge_smoke"


@dataclass(frozen=True)
class SmokeCase:
    name: str
    plan: Path
    project_path: Path
    expect_failure: bool = False
    expected_code: str | None = None
    expected_applied: int | None = None


def add_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "--targets",
        nargs="+",
        choices=("avatar", "world", "all"),
        default=["all"],
        help="Smoke targets. 'all' expands to avatar + world.",
    )
    parser.add_argument(
        "--avatar-plan",
        default=str(_default_plan_path("avatar")),
        help="Patch plan for avatar target.",
    )
    parser.add_argument(
        "--world-plan",
        default=str(_default_plan_path("world")),
        help="Patch plan for world target.",
    )
    parser.add_argument(
        "--avatar-project-path",
        default=str(_default_project_path("avatar")),
        help="Unity project path for avatar target.",
    )
    parser.add_argument(
        "--world-project-path",
        default=str(_default_project_path("world")),
        help="Unity project path for world target.",
    )
    parser.add_argument(
        "--avatar-expect-failure",
        action="store_true",
        help="Pass --expect-failure for avatar target.",
    )
    parser.add_argument(
        "--world-expect-failure",
        action="store_true",
        help="Pass --expect-failure for world target.",
    )
    parser.add_argument(
        "--avatar-expected-applied",
        type=int,
        default=None,
        help="Optional expected data.applied value for avatar target.",
    )
    parser.add_argument(
        "--world-expected-applied",
        type=int,
        default=None,
        help="Optional expected data.applied value for world target.",
    )
    parser.add_argument(
        "--avatar-expected-code",
        default=None,
        help="Optional expected response code value for avatar target.",
    )
    parser.add_argument(
        "--world-expected-code",
        default=None,
        help="Optional expected response code value for world target.",
    )
    parser.add_argument(
        "--expect-applied-from-plan",
        action="store_true",
        help=(
            "Infer expected applied count from patch plan ops length for non-failure targets "
            "when target-specific expected-applied is not provided."
        ),
    )
    parser.add_argument(
        "--python",
        default=sys.executable,
        help="Python executable used for child scripts.",
    )
    parser.add_argument(
        "--smoke-script",
        default=str(UNITY_BRIDGE_SMOKE_SCRIPT),
        help="Path to scripts/unity_bridge_smoke.py.",
    )
    parser.add_argument(
        "--bridge-script",
        default=str(Path("tools") / "unity_patch_bridge.py"),
        help="Path to tools/unity_patch_bridge.py.",
    )
    parser.add_argument(
        "--unity-command",
        default=None,
        help="Optional UNITYTOOL_UNITY_COMMAND override.",
    )
    parser.add_argument(
        "--unity-execute-method",
        default=DEFAULT_EXECUTE_METHOD,
        help="UNITYTOOL_UNITY_EXECUTE_METHOD value for all targets.",
    )
    parser.add_argument(
        "--unity-timeout-sec",
        type=int,
        default=None,
        help="Optional fallback UNITYTOOL_UNITY_TIMEOUT_SEC override for all targets.",
    )
    parser.add_argument(
        "--avatar-unity-timeout-sec",
        type=int,
        default=None,
        help="Optional UNITYTOOL_UNITY_TIMEOUT_SEC override for avatar target.",
    )
    parser.add_argument(
        "--world-unity-timeout-sec",
        type=int,
        default=None,
        help="Optional UNITYTOOL_UNITY_TIMEOUT_SEC override for world target.",
    )
    parser.add_argument(
        "--timeout-profile",
        default=None,
        help="Optional timeout profile JSON generated by smoke-history.",
    )
    parser.add_argument(
        "--max-retries",
        type=int,
        default=0,
        help="Retry count for transient smoke failures per target (default: 0).",
    )
    parser.add_argument(
        "--retry-delay-sec",
        type=float,
        default=0.0,
        help="Delay seconds between retries (default: 0.0).",
    )
    parser.add_argument(
        "--out-dir",
        default=str(DEFAULT_OUT_DIR),
        help="Output root directory for per-target artifacts and summary.",
    )
    parser.add_argument(
        "--summary-json",
        default=None,
        help="Optional summary JSON output path (default: <out-dir>/summary.json).",
    )
    parser.add_argument(
        "--summary-md",
        default=None,
        help="Optional summary Markdown output path.",
    )


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="bridge_smoke_samples",
        description="Run unity_bridge_smoke.py for sample avatar/world cases.",
    )
    add_arguments(parser)
    return parser


def _validate_batch_args(args: argparse.Namespace, parser: argparse.ArgumentParser) -> None:
    """Validate range constraints on all batch CLI arguments."""
    if args.max_retries < 0:
        parser.error("--max-retries must be greater than or equal to 0.")
    if args.retry_delay_sec < 0.0:
        parser.error("--retry-delay-sec must be greater than or equal to 0.")

    timeout_args = {
        "--unity-timeout-sec": args.unity_timeout_sec,
        "--avatar-unity-timeout-sec": args.avatar_unity_timeout_sec,
        "--world-unity-timeout-sec": args.world_unity_timeout_sec,
    }
    for arg_name, arg_value in timeout_args.items():
        if arg_value is not None and arg_value <= 0:
            parser.error(f"{arg_name} must be greater than 0.")
    expected_applied_args = {
        "--avatar-expected-applied": args.avatar_expected_applied,
        "--world-expected-applied": args.world_expected_applied,
    }
    for arg_name, arg_value in expected_applied_args.items():
        if arg_value is not None and arg_value < 0:
            parser.error(f"{arg_name} must be greater than or equal to 0.")
    expected_code_args = {
        "--avatar-expected-code": args.avatar_expected_code,
        "--world-expected-code": args.world_expected_code,
    }
    for arg_name, arg_value in expected_code_args.items():
        if arg_value is not None and not str(arg_value).strip():
            parser.error(f"{arg_name} must be non-empty when specified.")


def _render_markdown_summary(payload: dict[str, Any]) -> str:
    data = payload.get("data", {})
    cases = data.get("cases", [])
    timeout_profile_path = data.get("timeout_profile_path")
    lines = [
        "# Unity Bridge Smoke Batch",
        "",
        f"- Success: {payload.get('success')}",
        f"- Severity: {payload.get('severity')}",
        f"- Code: {payload.get('code')}",
        f"- Message: {payload.get('message')}",
        f"- Total: {data.get('total_cases', 0)}",
        f"- Passed: {data.get('passed_cases', 0)}",
        f"- Failed: {data.get('failed_cases', 0)}",
        (
            f"- Timeout Profile: {timeout_profile_path}"
            if timeout_profile_path
            else "- Timeout Profile: n/a"
        ),
        "",
        "| case | matched | expected_code | actual_code | code_matches | expected_applied | expected_source | actual_applied | applied_matches | attempts | duration_sec | timeout_sec | timeout_source | exit_code | response_code | response_path | unity_log_file |",
        "| --- | --- | --- | --- | --- | ---: | --- | ---: | --- | ---: | ---: | ---: | --- | ---: | --- | --- | --- |",
    ]

    def _cell(val: Any) -> Any:
        return "" if val is None else val

    for case in cases:
        lines.append(
            "| {name} | {matched} | {expected_code} | {actual_code} | {code_matches} | {expected_applied} | {expected_applied_source} | {actual_applied} | {applied_matches} | {attempts} | {duration_sec} | {timeout_sec} | {timeout_source} | {exit_code} | {response_code} | {response_path} | {unity_log_file} |".format(
                name=case.get("name", ""),
                matched=case.get("matched_expectation", False),
                expected_code=_cell(case.get("expected_code")),
                actual_code=_cell(case.get("actual_code")),
                code_matches=_cell(case.get("code_matches")),
                expected_applied=_cell(case.get("expected_applied")),
                expected_applied_source=_cell(case.get("expected_applied_source")),
                actual_applied=_cell(case.get("actual_applied")),
                applied_matches=_cell(case.get("applied_matches")),
                attempts=case.get("attempts", 1),
                duration_sec=_cell(case.get("duration_sec")),
                timeout_sec=_cell(case.get("unity_timeout_sec")),
                timeout_source=case.get("timeout_source", ""),
                exit_code=case.get("exit_code", ""),
                response_code=case.get("response_code", ""),
                response_path=case.get("response_path", ""),
                unity_log_file=case.get("unity_log_file", ""),
            )
        )
    return "\n".join(lines) + "\n"


def _build_batch_summary(
    args: argparse.Namespace,
    cases: list[SmokeCase],
    results: list[dict[str, Any]],
    out_dir: Path,
    *,
    partial_error: Exception | None,
    timeout_profile_path: Path | None,
    timeout_profile_overrides: dict[str, int],
) -> tuple[dict[str, Any], Path]:
    """Build summary payload and write JSON/MD outputs.

    Returns ``(summary_payload, summary_json_path)``.
    """
    failed_cases = [item for item in results if not item["matched_expectation"]]
    all_passed = len(failed_cases) == 0 and partial_error is None
    summary_code = "SMOKE_BATCH_OK" if all_passed else "SMOKE_BATCH_FAILED"
    if partial_error is not None:
        summary_message = (
            f"Batch aborted after {len(results)}/{len(cases)} cases: {partial_error}"
        )
    elif all_passed:
        summary_message = "All bridge smoke cases matched expectations."
    else:
        summary_message = "Some bridge smoke cases failed to match expectations."
    summary_payload: dict[str, Any] = {
        "success": all_passed,
        "severity": "info" if all_passed else "error",
        "code": summary_code,
        "message": summary_message,
        "data": {
            "total_cases": len(cases),
            "completed_cases": len(results),
            "passed_cases": len(results) - len(failed_cases),
            "failed_cases": len(failed_cases),
            "partial": partial_error is not None,
            "timeout_profile_path": (
                str(timeout_profile_path) if timeout_profile_path is not None else None
            ),
            "timeout_profile_targets": sorted(timeout_profile_overrides.keys()),
            "cases": results,
        },
        "diagnostics": [],
    }

    summary_json = Path(args.summary_json) if args.summary_json else out_dir / "summary.json"
    summary_json.parent.mkdir(parents=True, exist_ok=True)
    summary_json.write_text(
        dump_json(summary_payload),
        encoding="utf-8",
    )

    if args.summary_md:
        summary_md = Path(args.summary_md)
        summary_md.parent.mkdir(parents=True, exist_ok=True)
        summary_md.write_text(
            _render_markdown_summary(summary_payload),
            encoding="utf-8",
        )

    return summary_payload, summary_json


def run_from_args(args: argparse.Namespace, parser: argparse.ArgumentParser) -> int:
    _validate_batch_args(args, parser)

    timeout_profile_path: Path | None = None
    timeout_profile_overrides: dict[str, int] = {}
    if args.timeout_profile:
        timeout_profile_path = Path(args.timeout_profile)
        if not _wsl_path_exists(timeout_profile_path):
            parser.error(f"--timeout-profile not found: {timeout_profile_path}")
        try:
            timeout_profile_overrides = _load_timeout_profile_map(timeout_profile_path)
        except (OSError, json.JSONDecodeError, ValueError) as exc:
            parser.error(f"Failed to parse --timeout-profile: {exc}")

    smoke_script = Path(args.smoke_script)
    bridge_script = Path(args.bridge_script)
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    cases = _build_cases(args)
    results, partial_error = _execute_batch_cases(
        args,
        cases,
        out_dir,
        smoke_script=smoke_script,
        bridge_script=bridge_script,
        timeout_profile_overrides=timeout_profile_overrides,
    )

    summary_payload, summary_json = _build_batch_summary(
        args,
        cases,
        results,
        out_dir,
        partial_error=partial_error,
        timeout_profile_path=timeout_profile_path,
        timeout_profile_overrides=timeout_profile_overrides,
    )

    if partial_error is not None:
        raise partial_error

    print(summary_json)
    return 0 if summary_payload["success"] else 1


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    return run_from_args(args, parser)


if __name__ == "__main__":
    raise SystemExit(main())
